// Regenerates apps-script/ContentSeed.gs from the site's built-in text (js/i18n*.js) and the order/sections of
// index.html. Run `node apps-script/build-seed.js` after changing any text in those files, then redeploy the script
// (see README) and POST {"type":"rebuild"}: cells staff have not edited follow the new text, edited cells are kept.
const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..');
global.window = {};
require(path.join(root, 'js/i18n.js'));
require(path.join(root, 'js/i18n-tours.js'));
const I = window.I18N, LANGS = ['en', 'lo', 'th', 'zh', 'ko', 'ja', 'fr', 'de'];
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');

// Region markers in page order; each text belongs to the last marker before it.
const markers = [];
const add = (re, name) => { for (const m of html.matchAll(re)) markers.push([m.index, name]); };
add(/<header class="site-header"/g, "1. Menu bar");
add(/<section class="hero"/g, '2. Top of the page');
add(/<section class="tour" id="tour"/g, '3. Tours (headings)');
for (const [id, name] of [['t101', 'Tour 101 card'], ['t102', 'Tour 102 card'], ['t103', 'Tour 103 card'], ['t001', 'Tour 001 card (1-day boat trip)']]) {
  const at = html.indexOf(`id="${id}"`);
  markers.push([at, '3. ' + name]);
  markers.push([html.indexOf('</article>', at), '3. Tours (headings)']);
}
add(/class="info" id="info"/g, '4. Good to know');
add(/<section class="story"/g, '5. Our story');
add(/<section class="gallery"/g, '6. Gallery');
add(/<section class="reviews"/g, '7. Reviews');
add(/<section class="faq" id="faq"/g, '8. FAQ');
add(/class="policy reveal" id="policy"/g, '9. Booking & cancellation policy');
add(/<section class="book" id="book"/g, '10. Booking form & contact');
add(/<footer\b/g, '11. Footer');
markers.sort((a, b) => a[0] - b[0]);
const regionAt = pos => { let w = '12. Messages & labels built by the page'; for (const [at, name] of markers) if (at <= pos) w = name; return w; };
const order = [], seen = {};
for (const m of html.matchAll(/data-i18n(?:-html|-ph)?="([^"]+)"/g)) {
  const key = m[1], w = regionAt(m.index);
  if (!seen[key]) { seen[key] = new Set(); order.push(key); }
  seen[key].add(w);
}
// Text used in several tour cards is shared by those tours: say so instead of naming the first card.
const region = {};
for (const key of order) {
  const cards = [...seen[key]].filter(w => /Tour \d+ card|Tour 001 card/.test(w));
  region[key] = cards.length > 1 ? '3. Tour cards (shared by several tours)' : [...seen[key]][0];
}
for (const key of Object.keys(I.en)) if (!region[key]) { region[key] = '12. Messages & labels built by the page'; order.push(key); }
const rows = order.filter(k => I.en[k] != null).map(k => [k, region[k]].concat(LANGS.map(l => (I[l][k] != null ? I[l][k] : I.en[k]))));
fs.writeFileSync(path.join(__dirname, 'ContentSeed.gs'),
  '// GENERATED by build-seed.js from js/i18n*.js and index.html. Do not edit by hand.\n' +
  'var CONTENT_SEED = [\n' + rows.map(r => '  ' + JSON.stringify(r)).join(',\n') + '\n];\n');
const bySection = {}; rows.forEach(r => bySection[r[1]] = (bySection[r[1]] || 0) + 1);
console.log(rows.length + ' rows'); console.log(bySection);
